const constants = {
  CLEAR_RESULTS: "CLEAR_RESULTS",
  FETCH_PENDING: "FETCH_PENDING",
  FETCH_CANCEL: "FETCH_CANCEL",
  SEARCH_ERROR: "SEARCH_ERROR",
  SEARCH_NOMATCH: "SEARCH_NOMATCH",
  SET_POKEMON: "SET_POKEMON",
  UPDATE_SEARCHINPUT: "UPDATE_SEARCHINPUT",
};

export default constants;