const constants = {
  CLEAR_RESULTS: "CLEAR_RESULTS",
  FETCH_PENDING: "FETCH_PENDING",
  FETCH_CANCEL: "FETCH_CANCEL",
  GET_UNIVERSE: "GET_UNIVERSE",
  SEARCH_ERROR: "SEARCH_ERROR",
  SET_POKEMON: "SET_POKEMON",
  UPDATE_SEARCHINPUT: "UPDATE_SEARCHINPUT",
  ADD_POKEMON: "ADD_POKEMON",
  REMOVE_POKEMON: "REMOVE_POKEMON"
};

export default constants;